### ISSUE TITLE
Support https proxy

### ISSUE THREAD

**Issue by cp2587** [scrapinghub/splash#549]
Hi,

Thank you very much for this library. I must say you made tremendous update on it since last time i tried to use it (we stopped using it one year ago because it was too troublesome to use with proxies). 
It seems like splash does not yet support proxies that use the https or connect method. Is that something you can easily add or not ? Are you open to a PR for something like this ?

Best,

**Comment by kmike** [comment]
Hey @cp2587,

Splash should support HTTPS proxies via CONNECT method; use 'HTTP' type for them. There are no tests for them, but I checked it manually when implementing this feature (ir worked), and it is a documented feature (see http://splash.readthedocs.io/en/stable/scripting-request-object.html#splash-request-set-proxy).

**Comment by cp2587** [comment]
But how does splash know it must test for the CONNECT method ?

**Comment by kmike** [comment]
It is implemented in Qt, so I'm not 100% sure my explanation is correct. Buf AFAIK if the requested URL uses https scheme Splash (Qt, actually) tries to use CONNECT method.

**Comment by cp2587** [comment]
Indeed, requesting an https endpoint work when using a proxy of the form http://xxxx (i am using scrapy) but i was referrering about using a proxy of the form https://xxx (but maybe this a dumb question because all proxy should also support http ?)  
As a side note, i cannot figure out how to make my crawlera account work with splash for https requests. Is this because i need to install the crawlera ssl certficate somewhere on splash server ?

**Comment by kmike** [comment]
> Indeed, requesting an https endpoint work when using a proxy of the form http://xxxx (i am using scrapy) but i was referrering about using a proxy of the form https://xxx (but maybe this a dumb question because all proxy should also support http ?)

Again, I'm not 100% sure, but it seems http/https is not relevant for proxies; what is important is the ip address browser will connect to.

> As a side note, i cannot figure out how to make my crawlera account work with splash for https requests. Is this because i need to install the crawlera ssl certficate somewhere on splash server ?

A good question; I haven't tried it. Crawlera+Splash [docs](https://doc.scrapinghub.com/crawlera.html#using-crawlera-with-splash) say nothing about that (unlike e.g. crawlera+requests docs), so I expected it to work as-is.

**Comment by cp2587** [comment]
OK. It does not work for me :) 
I opened a relevent ticket on scrapinghub: https://support.scrapinghub.com/topics/2402-/ 

Seems like most of the proxies i am using work well with splash. I only have some of them for which i have trouble but it's because of the CONNECT method... Thanks for the replies !

**Comment by kmike** [comment]
Hey @cp2587,

I've fixed a bug which could have caused problems with HTTPS + Crawlera; if you still need it, could you please check if Splash 2.3.1 works for you? I think updated Docker images will be available in ~a hour.

**Comment by cp2587** [comment]
Ok ! i will let you know. Thanks !

**Comment by cp2587** [comment]
Still no luck :/
I tried with the following adress: http://ipinfo.io. It always return a 200 response with a body as follow: '<html><head></head><body></body></html>'

**Comment by kmike** [comment]
@cp2587 here is a basic snippet: https://github.com/scrapinghub/splash/issues/559#issuecomment-274208009. There is a couple more elaborate snippets here: https://github.com/scrapinghub/splash/issues/559#issuecomment-274599777

**Comment by kmike** [comment]
There is also an example using Crawlera + Splash + Python requests in https://doc.scrapinghub.com/crawlera.html#using-crawlera-with-splash

**Comment by kmike** [comment]
`<html><head></head><body></body></html>` usually means Crawlera authentication failed; this happens either because of bad credentials, bad formatting of proxy URL or because of Splash bugs (should be fixed in 2.3.1).

**Comment by cp2587** [comment]
Ok... The first snippet (most basic one with requests) works ! So i guess i am doing something wrong with scrapy. Thanks a lot, i keep you updated !

**Comment by kmike** [comment]
Are you using scrapy-splash? Here is another example Splash + Crawlera + Scrapy script: https://github.com/scrapy-plugins/scrapy-splash/issues/97#issuecomment-268647494

**Comment by cp2587** [comment]
I found the bug ! I was missing the ':' at the end of the proxy_url (because crawlera does not have a password). Thank you so much for your work :) 
You can close this issue ! Have a great day

**Comment by kmike** [comment]
Woohoo, thanks for checking it!

**Comment by ssudheeshsparksupport** [comment]
Trusted proxy rotation is not working with flash(Every time I get the same ip). I have tried this (http://splash.readthedocs.io/en/latest/api.html#proxy-profiles) also but it is not working.
